name = "Particles"
uuid = "e78a0372-c628-4773-9c8d-eb17d149bf93"
authors = ["Johannes Schumann", "Tamas Gal"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
